### ISSUE TITLE
Automatically adding star (*) sometimes on UI instead of image

### ISSUE THREAD

**Issue by AbhaysinghBhosale** [Sitebase/react-avatar#155] opened 2019-02-27 11:40 UTC
I have used this packages to load the images from local directory. but sometimes it renders the following html inside sb-avatar class which shows start symbol in the box.

`<div class="pull-left mt-1 sb-avatar__text" style="width: 100px;height: 100px;font-size: 33.3333px;line-height: 100px;text-align: center;text-transform: uppercase;color: rgb(255, 255, 255);background: rgb(103, 174, 63);">✷</div>`

**Comment by JorgenEvens** [comment] 2019-02-27 16:27
Hi @AbhaysinghBhosale,

The asterisk is rendered as part of the `Icon` source whenever non of the other properties give us enough information to render an avatar or a text value. Could you double-check that you are not getting any not-found errors on these images?

**Comment by AbhaysinghBhosale** [comment] 2019-04-04 10:55
> Hi @AbhaysinghBhosale,
> 
> The asterisk is rendered as part of the `Icon` source whenever non of the other properties give us enough information to render an avatar or a text value. Could you double-check that you are not getting any not-found errors on these images?

Hi @JorgenEvens I have checked the code and there is no any such issue. Images are there in folder and this only happens sometimes. Even the images is there this is occuring

**Comment by JorgenEvens** [comment] 2019-04-04 12:26
Hi @AbhaysinghBhosale,

Could you create a small project that reproduces this issue such that I can investigate it further?

**Comment by alexdevero** [comment] 2019-04-18 13:29
I am also experiencing this issue. Dat for icon src and name are passed. However, the avatar contains only star (*).

**Comment by JorgenEvens** [comment] 2019-04-18 17:13
Hi @alexdevero,

Would you be able to create a sample that shows the star when it should actually not do so on [codesandbox](https://codesandbox.io/) or something similar?

**Comment by alexdevero** [comment] 2019-04-19 04:01
@JorgenEvens I probably know what is the problem. Avatar is rendered before it knows the value for `src`, and the `name` is not used.

I am using API calls and promises in my project and these calls sometimes takes longer. The demo below confirms my assumption. The promise is called, but the valued is return **after** the `avatar` component is called. And, since there is no `name` as a fallback, the "*" is rendered instead.

Demo:
https://codesandbox.io/s/140rmxkjvj

So, it is not problem with `react-avatar`, at least not in my case.

**Comment by JorgenEvens** [comment] 2019-04-19 07:22
Hi @alexdevero,

Thanks for getting back with a demo. As you mentioned the value of avatar is not yet set when the avatar is rendered.

What I would suggest in situations like the demo you provided is to use either [React Hooks](https://github.com/RuntimeTools/appmetrics/issues/505) or [Component classes and their `setState`](https://reactjs.org/docs/state-and-lifecycle.html) to ensure that your component is re-rendered properly.

**Comment by alexdevero** [comment] 2019-04-19 11:11
Hi @JorgenEvens. Thank you for your suggestions. React hook are currently the option I prefer the most. The last question is if the issue addressed by @AbhaysinghBhosale is similar to the one demonstrated in the demo or not.

@AbhaysinghBhosale?

**Comment by JorgenEvens** [comment] 2019-09-15 01:03
Since the issue @alexdevero has been resolved and I haven't heard back from @AbhaysinghBhosale I'll be closing this issue. Feel free to leave a comment if any new information becomes available.

**Closed by JorgenEvens** 2019-09-15 01:03 UTC
Labels: bug, incomplete
