### ISSUE TITLE
src property not working

### ISSUE THREAD

**Issue by EndStatement** [Sitebase/react-avatar#137] opened 2018-10-05 14:58 UTC
Image not showing here's my code:
`<Avatar src={localStorage.getItem('imgURL')}
               name={localStorage.getItem('companyName')}
               round/>`

Also tried to put string url on src but it same result

**Comment by JorgenEvens** [comment] 2018-10-05 16:12
Hi @HumbleCarl,

Could you provide me with a more detailed reproduction case, including which version of React and React-Avatar you are using.

The reproduction I've made does not suffer from the problem you are describing. See https://codesandbox.io/s/lpp02p1zpl

If you are testing this on a recent version of Chrome you should verify that the `Content-Type` header on the image is set correctly as chrome implements [CORB](https://chromium.googlesource.com/chromium/src/+/master/services/network/cross_origin_read_blocking_explainer.md). We experience the same a while back when loading the Twitter avatars.

**Comment by mongrelx** [comment] 2018-10-07 20:49
Same problem react 16.5.2 react-avatar 3.4.4

**Comment by JorgenEvens** [comment] 2018-10-07 22:12
@mongrelx Do you have an image for me to test this with? As you can see in the codesandbox, a regular image loads just fine for me.

**Comment by JorgenEvens** [comment] 2018-12-16 00:54
@EndStatement @mongrelx Are you still experiencing an issue with this?

**Comment by JorgenEvens** [comment] 2019-02-15 21:44
This issue has been open for some time, I'm closing it now. Feel free to comment on this issue if you have any new information.

**Comment by mmm1key** [comment] 2019-03-14 11:37
I found the same problem if the URL contains numbers.

Not working src-property: http://res.cloudinary.com/bdv/image/upload/6

Working src-property: http://res.cloudinary.com/bdv/image/upload/sample

**Comment by JorgenEvens** [comment] 2019-03-14 16:55
Hi @mmm1key,

Could you let me know which version of react and react-avatar you are using, I'm unable to reproduce your issue using those links. (see [here](https://codesandbox.io/s/o4x49rl8zz)).

If at all possible could you create a simple [codesandbox](https://codesandbox.io) that is not working for you?

**Comment by mmm1key** [comment] 2019-03-15 11:26
Hello @JorgenEvens,

if I start your codesandbox project with "npm start" everything works fine, but if I start your project with Visual Studio Code the output looks like this:

![image](https://user-images.githubusercontent.com/48554212/54428264-4217f200-471d-11e9-9729-b240244d50d3.png)

I think it's a bug in Visual Studio Code! ;-)

**Comment by JorgenEvens** [comment] 2019-09-15 00:46
Since no new information has come to light regarding this issue I'm closing it again. As previously, feel free to leave a comment when any new information becomes available.

**Closed by JorgenEvens** 2019-09-15 00:46 UTC
Labels: incomplete
