### ISSUE TITLE
Showing ? for broken image url and same url cannot load multiple time cause of browser cash

### ISSUE THREAD

**Issue by amdad77682** [Sitebase/react-avatar#193] opened 2020-02-19 12:36 UTC
For any url that was fail to load this avatar show ? symbol  

same url cannot render multiple time in a multiple react component in same page  

https://codesandbox.io/s/hungry-ardinghelli-8jtrx?fontsize=14&hidenavigation=1&theme=dark

**Comment by JorgenEvens** [comment] 2020-02-20 00:00
Hi @amdad77682,

The intended behavior of this component is to fall back to an icon (usually `*`) when a resource fails to load.

Could you set up a [codesandbox](https://codesandbox.io/) to illustrate your problem?

**Comment by JorgenEvens** [comment] 2020-04-23 22:41
Hi @amdad77682 ,

Your questions seems very similar to that in https://github.com/Sitebase/react-avatar/issues/196, so I'll be closing this issue.

Please feel free to leave a comment if the answers in that thread don't help in your use-case.

**Closed by JorgenEvens** 2020-04-23 22:41 UTC
Labels: incomplete
