### ISSUE TITLE
version 3.0.0 console.log in utils.js file

### ISSUE THREAD

**Issue by ptboyer** [Sitebase/react-avatar#104] opened 2018-06-05 04:46 UTC
When using `react-avatar@3.0.0` a `console.log` has been left in, and it needlessly pollutes the console ([utils.js#L101](https://github.com/Sitebase/react-avatar/blob/f19e06a0bd3e172f2851b2c7c1f72dae233ca9b3/lib/utils.js#L101)).

**Comment by JorgenEvens** [comment] 2018-06-05 04:47
Duplicate of https://github.com/Sitebase/react-avatar/issues/102

**Closed** 2018-06-05 04:47 UTC

**Comment by Sitebase** [comment] 2018-06-05 07:19
This issue is resolved in version `3.0.1`
