### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object

### ISSUE THREAD

**Issue by ifeanyidavid** [Sitebase/react-avatar#120] opened 2018-08-30 12:10 UTC
I recently updated to react 16.4.2 then I got this error: `Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `withAvatarConfig`.`

**Comment by JorgenEvens** [comment] 2018-09-08 14:11
Hi @ifeanyidavid, thanks for the bug report. I am however having some issues reproducing this.
Upgrading the demo to 16.4.2 does not reveal any issues in the `withAvatarConfig` component.

What version of `react-avatar` are you using?
Could you share what your code looks like or provide a reproduction case for this issue as well?

If you are unsure how to use the `ConfigProvider`, please see the section [Configuring React Avatar globally](https://github.com/Sitebase/react-avatar#usage) on how to use it.

**Comment by JorgenEvens** [comment] 2018-09-08 16:36
@madhusudhan1234 , so you are having this happen without even using the `ConfigProvider` ?

**Comment by madhusudhan1234** [comment] 2018-09-12 15:36
@JorgenEvens  Thank You, Now it works using avatar-redirect for twitter avatar. Cheers!

**Comment by JorgenEvens** [comment] 2019-02-08 23:43
As I am unable to reproduce this issue I'm going to close this for now. If you are still experiencing this issue and are able to provide more information please feel free to re-open / comment on this issue.

**Closed by JorgenEvens** 2019-02-08 23:43 UTC
Labels: bug, incomplete
